server:
  port: 8081
spring:
  profiles:
    active: test
---
server:
  port: 8884
spring:
  profiles: dev
---
server:
  port: 8885
spring:
  profiles: test

student:
  name: zhangsan
  age: 23
  sex: true
  birthday: 2019/03/12
  location: {province: 陕西,city: 西安,zone: 莲湖区}
  hobbies:
      - 足球
      - 篮球
  skills:
      - 编程
      - 金融
  pet:
    nickname: wc
    strain: hsq
